name: Deploy to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main   # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Optional: Build step if you use a static site generator or bundler
    # - name: Build site
    #   run: |
    #     npm install
    #     npm run build

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: YOUR_AWS_REGION  # e.g. us-east-1

    - name: Sync files to S3
      run: |
        aws s3 sync ./public s3://YOUR_S3_BUCKET_NAME --delete
      # Replace ./public with your build output folder if applicable

    - name: Create CloudFront Invalidation
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
